# -*- coding: utf-8 -*-
#
# IC-SwitchWare documentation build configuration file, created by
# sphinx-quickstart on Mon Mar 15 15:22:44 2021.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.intersphinx',
              'sphinx.ext.todo',
              'sphinx.ext.mathjax',
              'sphinx.ext.ifconfig',
              'sphinx.ext.graphviz',
              'sphinxcontrib.plantuml',
              'sphinx_rtd_theme',
              'sphinx.ext.autosectionlabel',
              'breathe']
              # 'docxbuilder']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Enbox'
copyright = u"2022, Interface Concept"
author = u"Grégor Boirie"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
#version = u'1.0'
version = os.getenv('VERSION', u'??')

# The full version, including alpha/beta/rc tags.
#release = u'1.0'
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Setup base URL for manpage role -------------------------------------------
# see https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-manpage
manpages_url = "https://man7.org/linux/man-pages/man{section}/{page}.{section}.html"

# -- Options for breathe output -------------------------------------------
doxy_xml_path = os.getenv('DOXY_XML_PATH')
if not os.path.isdir(doxy_xml_path):
    print('{}: Invalid Doxygen XML directory'.format(os.path.basename(sys.argv[0])),
          file=sys.stderr)
    sys.exit(1)

breathe_default_project        = project
breathe_projects               = { breathe_default_project: doxy_xml_path }
breathe_domain_by_extension    = { "h" : "c", "c": "c" }
breathe_show_include           = False
breathe_order_parameters_first = True
breathe_separate_member_pages  = False
breathe_default_members        = ('members', 'undoc-members')

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
        'collapse_navigation': False,
        'sticky_navigation': True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ICSWdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    'passoptionstopackages': r'\PassOptionsToPackage{svgnames}{xcolor}',
    'sphinxsetup': r'''%
         TitleColor={named}{Black},
         ''',
    #      verbatimwithframe=false,
    #      VerbatimColor={named}{OldLace},
    #      TitleColor={named}{Dark},
    #      hintBorderColor={named}{LightCoral},
    #      attentionborder=3pt,
    #      attentionBorderColor={named}{Crimson},
    #      attentionBgColor={named}{FloralWhite},
    #      noteborder=2pt,
    #      noteBorderColor={named}{Olive},
    #      cautionborder=3pt,
    #      cautionBorderColor={named}{Cyan},
    #      cautionBgColor={named}{LightCyan}

    # Additional stuff for the LaTeX preamble.
    #
    'preamble': r"""
\usepackage[cm]{fullpage}
\usepackage{lastpage}
\usepackage{datetime2}
 \usepackage{calc}

\hypersetup{
    colorlinks = false,
    linkbordercolor = {white},
}

\geometry{hscale=1, vscale=1,
    top=4cm, head=1.75cm, headsep=1cm,
    bottom=3cm, foot=1.5cm,
    left=1in, right=1in,
}

\usepackage{setspace}
\usepackage{array}
\usepackage{tabularx}
\makeatletter
\fancypagestyle{normal}{
  \fancyhf{}
  \fancyhead[c]{
    \begin{tabularx}{\textwidth}{|c|X|m{2.5cm}|m{2cm}|}
    \hline
    \begin{minipage}{4.5cm}
      \vspace{1mm}
      \sphinxlogo
    \end{minipage} &
    \begin{tabular}{@{}l@{}}\@title \\ Version \version \end{tabular} & 
    \begin{tabular}{@{}l@{}}$\checkmark$ confidential \\$\square$ internal \\$\square$ free\end{tabular} & 
    MD0502A \\ 
    \hline
    \end{tabularx}
   }
  \renewcommand{\footrulewidth}{1pt}
  \fancyfoot[l]{\setstretch{0.6}
    \jobname.tex \\ 
    {\scriptsize
    This document is the property of Interface Concept and cannot be reproduced
    without prior consent of Interface Concept. 
    }}
  \fancyfoot[r]{Page: \thepage/\pageref*{LastPage}}
}
\fancypagestyle{ictitle}
{
   \fancyhf{}
   \renewcommand{\footrulewidth}{1pt}
   \fancyfoot[c]{
      {\footnotesize
        3 rue Félix Le Dantec - 29000 Quimper - France - 
        Tel. +33 (0)2 98 57 30 30 - Fax +33 (0)2 98 57 30 00\\
        SAS capital de 283 256 € – RCS Quimper B 341 722 197 – 
        NAF 2620 Z – N° TVA FR 84 341 722 197\\
        www.interfaceconcept.com
      }
    }
}
\makeatother
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{3}
\DTMsetstyle{yyyymd}
\DTMsetup{datesep=/}
\newcolumntype{Y}{>{\centering\arraybackslash}X}
    """,

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
    'tableofcontents': r'''
\pagestyle{normal}
\renewcommand\contentsname{
    \begin{center}
        TABLE OF CONTENTS
    \end{center}
}
\tableofcontents
\clearpage
    ''',
    # 'atendofbody': ""
    'maketitle': r'''
\makeatletter
\begin{titlepage}%
    \newgeometry{nohead, top=2.5cm, bottom=4.15cm, left=1in, right=2cm,}
    \thispagestyle{ictitle}
    \let\footnotesize\small
    \let\footnoterule\relax
    \begingroup % for PDF information dictionary
        \def\endgraf{ }\def\and{\& }%
        \pdfstringdefDisableCommands{\def\\{, }}% overwrite hyperref setup
        \hypersetup{pdfauthor={\@author}, pdftitle={\@title}}%
    \endgroup
    \begin{center}%
        \sphinxlogo
        \vfill
        \vspace{15mm}
        {\setlength{\fboxsep}{0pt}%
        \setlength{\fboxrule}{2pt}%
        \fbox{
        \parbox[][8.6cm][c]{10.16cm}{\center
        \py@HeaderFamily
        {\LARGE \@title \par}
        }}}
        \vfill
    \end{center}%\par
    \restoregeometry
\end{titlepage}%
\pagestyle{normal}
\newgeometry{top=4cm, bottom=3cm, left=1in, right=1in,}
{\setlength{\fboxsep}{2pt}%
    \setlength{\fboxrule}{2pt}%
    \fbox{
        \parbox[][2cm][l]{\textwidth-6\fboxsep}{\Large\hspace*{1em} Recipients:}
    }
}
\section*{
        \begin{center}
        EVOLUTION OF VERSION
    \end{center}
}
\begin{tabularx}{\textwidth}{|c|c|c|c|X|}
\hline
\textbf{Version} & \textbf{Date} & \textbf{Created by} & 
\textbf{Checked by} & 
{\begin{tabularx}{\linewidth}{@{}Y@{}}\textbf{Comments}\end{tabularx}} \\
\hline
\version & \today & \@author & & Auto gen version \\
\hline
\end{tabularx}
\clearpage
\restoregeometry
\makeatother
    '''
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, '399_IC_SwitchWare_Documentation.tex', u'IC-SwitchWare Documentation',
     author, 'howto'),
]
latex_logo = "IC-Int-Adv_HD.jpg"
latex_show_urls = 'footnote'
latex_show_pagerefs = True

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'icsw', u'IC-SwitchWare Documentation',
     author, 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'IC-SwitchWare', u'IC-SwitchWare Documentation',
     author, 'icsw', '',
     'Miscellaneous'),
]

# docx_documents = [
#     ('index', 'icsw.docx', {
#          'title': 'IC-SwitchWare',
#          'creator': author,
#          'subject': 'IC-SwitchWare Documentation',
#      }, True),
# ]
# docx_style = 'MD0502_Document_uk.dotx'
# docx_pagebreak_before_section = 1

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}
